### PR TITLE
Changed Nav to be icons

### PR DESCRIPTION
**Pull request by veddermatic**
Made app not render calculator that was not being used
Changed lodash imports to only bring in used functions
Centered content in browser window
Upgraded react-scripts mainly to get rid of webpack licence iframe
Moved some dev dependencies down in package.json
Added hillarious comment to commented out test

### CODE REVIEW

**Comment by jmegner** [comment]
Thanks for the pull request!

>Changed Nav to be icons

Can we have hovertext "Shoot" and "Fight"?  I'm addicted to hovertext for icons?  Also, are the engage and conceal order icons just for possible future use?

>Made app not render calculator that was not being used

Unfortunately that change also makes the shoot/fight section lose state when you swap to the other section.  Ex: you are in shoot section, change MWx to 1, then go to fight section and back to shoot section, and you'll see that MWx is back to X (the default).  I'd rather that users not lose work when toggling between shoot and fight sections.

>Changed lodash imports to only bring in used functions

Good idea.  Sidenote: you missed Util.ts, line 59, which uses `_` and caused a syntax error for me.

>Centered content in browser window

I like it.

>Upgraded react-scripts mainly to get rid of webpack licence iframe

Could you walk me through how you did this?  I think at one point I tried to do some upgrading of eslint and got so many issues I undid it.  At another point, I did some other upgrade (react itself?) and then I couldn't use tsconfig.json's `"baseUrl": "."` to get import paths more absolute (within the project), so I undid that too.  So, I have to ask if you did anything other than a `npm update react-scripts`?

Also, webpack license iframe, is that [this thing](https://stackoverflow.com/questions/70499543/create-react-app-creates-this-iframe-that-prevents-me-from-clicking-or-editing)?

>Moved some dev dependencies down in package.json

Interesting.  I can see why TypeScript and types packages are a dev dependency and not a runtime dependency, but now I'm confused why create-react-app would not put those things in devDependencies.  Any insight?

**Comment by jmegner** [comment]
Oh, also, the icons shouldn't be in src/, right?  maybe public/ or a subfolder of public?

**Comment by veddermatic** [comment]
> Can we have hovertext "Shoot" and "Fight"? I'm addicted to hovertext for icons? Also, are the engage and conceal order icons just for possible future use?

Done

> Good idea. Sidenote: you missed Util.ts, line 59, which uses _ and caused a syntax error for me.

Fixed. 

> Unfortunately that change also makes the shoot/fight section lose state when you swap to the other section

Oops, this is better now.

**Comment by veddermatic** [comment]
Images should be in `src` because they are imported, so they will be part of the build process.

**Comment by jmegner** [comment]
Thanks again!

**Pull request merged**
